version: '3'
services:
  mysql-db:
    container_name: mysql-db
    image: "mysql/mysql-server:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ONETIME_PASSWORD=true
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DB=dockerdemo

  springboot-mysql-app:
    container_name: springboot-mysql-app
    image: springboot-mysql-app:latest
    build:
      context: ./springboot-mysql-docker-compose
      dockerfile: Dockerfile
    working_dir: /springboot-mysql-docker-compose
    restart: on-failure
    ports:
      - "8088:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/dockerdemo?useSSL=false&allowPublicKeyRetrieval=true
    command: mvn clean spring-boot:run